### ISSUE TITLE
KeyError when running frame_transformer.detect_frames

### ISSUE THREAD

**Issue by Yangyi-Chen** [chanind/frame-semantic-transformer#12]
Great thanks for the contributions! The implemented semantic role labeling model helps me a lot!! 

Some small issue when using this tool is when I call the frame_transformer.detect_frames(SENTENCE). The KeyError occurs given some specific sentences.

The log: 
```
Traceback (most recent call last):
  File "/Users/CYY/opt/anaconda3/envs/ofa/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-0930869b8149>", line 1, in <module>
    frame_transformer.detect_frames("Fog is in the air at an intersection with several traffic lights.")
  File "/Users/CYY/opt/anaconda3/envs/ofa/lib/python3.8/site-packages/frame_semantic_transformer/FrameSemanticTransformer.py", line 138, in detect_frames
    return self.detect_frames_bulk([sentence])[0]
  File "/Users/CYY/opt/anaconda3/envs/ofa/lib/python3.8/site-packages/frame_semantic_transformer/FrameSemanticTransformer.py", line 216, in detect_frames_bulk
    return [results_map[parsed_sentences_map[sentence]] for sentence in sentences]
  File "/Users/CYY/opt/anaconda3/envs/ofa/lib/python3.8/site-packages/frame_semantic_transformer/FrameSemanticTransformer.py", line 216, in <listcomp>
    return [results_map[parsed_sentences_map[sentence]] for sentence in sentences]
KeyError: 'Fog is in the air at an intersection with several traffic lights.'
```
Some specific inputs that trigger this error: 
1. two cars parked on the sidewalk on the street
2. a modern flush toilet in a bathroom with tile.
3. Fog is in the air at an intersection with several traffic lights.
4. a man with a bike at a marina
5. four urinals in a public restroom with a window
6. a home office with laptop, printer, scanner, and extra monitor

Thanks!

**Comment by chanind** [comment]
I can reproduce this issue as well, I think this bug may have been introduced when adding bulk processing support. I'll work on a fix ASAP. Sorry for this bug, and thank you for reporting this!

**Comment by Yangyi-Chen** [comment]
Thanks David!
